dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.27.1/bazel-0.27.1-darwin-x86_64
  - echo "7c9129bf8f4b3e86c5f3dfbbdbbb96a058cd87577ce701d8ab94d81bdd6c86cd bazel-0.27.1-darwin-x86_64" | sha256sum -c
  - sudo dpkg -i bazel-0.27.1-darwin-x86_64

script:
  - bazel --bazelrc=.test-bazelrc test //...