dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - echo "6810fc4144292444721998ef777e058394908d0d11be6e15608262ff464b2c7c bazel_0.3.1-linux-x86_64.deb" | sha256sum -c
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
  - bazel --bazelrc=.test-bazelrc test //...