dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - sudo apt-get install bazel openjdk-9-jdk-

script:
  - bazel --bazelrc=.test-bazelrc test //...